theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
title: Elegance | Outfit ideas & Online Shopping for your online wardrobe
description: An application in which your wardrobe will become easily accessible (automatically categorized by size, color and type), clothes exchange with simple clicks , your outfits (summer outfit, hijab outfit...) will attract everyone and your online shopping experience will become the simplest and fastest.